### ISSUE TITLE
[bug] Missing "found = true;" statement in ParseCustomField

### ISSUE THREAD

**Issue by space2** [syoyo/tinydng#12]
In `ParseCustomField` in the rational case (i.e. `if ((type == TYPE_RATIONAL) || (type == TYPE_SRATIONAL)) {`) the `found = true;` statement seems to be missing.

**Comment by syoyo** [comment]
@space2 Nice catch! Fixed! https://github.com/syoyo/tinydngloader/commit/3fc433efa7b555b64c1bbd52464d5258fc58720d  Thanks!
