### ISSUE TITLE
[TODO] Compression for DNG writer!

### ISSUE THREAD

**Issue by storyboardcreativity** [syoyo/tinydng#20]
Please, implement compression for DNG writer if you have some time

You can find some code in DNG SDK. For example:
https://github.com/gopro/gpr/blob/master/source/lib/dng_sdk/dng_image_writer.cpp

**Comment by syoyo** [comment]
I don't have time for a while.

Your contribution is much appreciated!

**Comment by syoyo** [comment]
:pray: PR https://github.com/syoyo/tinydng/pull/23
