### ISSUE TITLE
Excessive Printing/Output

### ISSUE THREAD

**Issue by rajkundu** [syoyo/tinydng#21]
Hello! I just began using this library (it's great - thank you for it!), and I am getting excessive output to stdout when simply trying to load a TIFF file.

I see that the flag `TINY_DNG_LOADER_DEBUG` enables debug output. However, it seems that as of commit 9c10667, this flag has become [unconditionally enabled](https://github.com/syoyo/tinydng/blob/9c10667a696d8a919dc87f75a85cdef8ad75079d/tiny_dng_loader.h#L335).

Perhaps I am missing something, but should the linked line above be commented out as in previous commits?

**Comment by syoyo** [comment]
@rajkundu Good catch! Guess I've commit it by mistake. You can simply uncomment to suppress debug print for a while.
You can also send a PR to fix it!(simply delete/uncomment that line)

**Comment by rajkundu** [comment]
Made a PR at #22!
