### ISSUE TITLE
Add packbit support to tiff reading and writing

### ISSUE THREAD

**Issue by fire** [syoyo/tinydng#25]
Hi!

I was wondering if we can suggest adding packbits to this tiff reader

Some context https://github.com/godotengine/godot-proposals/issues/4620 and https://github.com/godotengine/godot-proposals/issues/5803.

**Comment by syoyo** [comment]
You can contribute! PR is much appreciated

**Comment by fire** [comment]
I am not able to, not familiar with the PackBit technology or your code base.
