### ISSUE TITLE
BUG: (very quick) #include <intrin.h> within the scope of the namespace tinydngwriter

### ISSUE THREAD

**Issue by JosipML** [syoyo/tinydng#30]
Please remove the include from line 107 in tiny_dng_writer.h:
#ifdef _MSC_VER
#include <intrin.h>        <----
...

and add it in front of the namespace tinydngwriter within the #ifdef clause as follows:

#ifdef _MSC_VER
#include <intrin.h>
#endif

Including it within the scope of the namespace causes issues with other includes like <algorithm> etc.

**Comment by JosipML** [comment]
I think it is a quite simple functionality as well and that the performance would remain probably very similar. I guess both solutions are good. For me only the include inside a namespace was causing issues causing unrelated errors to pop out.

**Comment by syoyo** [comment]
I have disabled using MSVC intrinsic functions.

If you find intrinsic functions are useful(gives noticeable performance gain), please send a  PR which controls using intrinsic functions with a macro something like

`TINY_DNG_USE_INTRINSIC`

**Comment by JosipML** [comment]
Thank you! I have tested it with our code quite extensively today and it seems to be very performant. We export images in the order of ~1000 images and it is very fast from a user perspective, especially in comparison with other file types like PNG.
